# -*- coding: utf-8 -*-
"""progetto machine learning 19/05/26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IRQ0KaZs2m6KqYWaw80V0jTlVPsdoY2

# Download dei dati
"""

#@title Righe da decommentare prima della consegna: fanno download sulla RAM di colab
# import gdown
# import os
# !mkdir -p processed_data
# fn_back=r"processed_data/events_LHCO2020_backgroundMC_Pythia.h5"
# url = "https://drive.google.com/uc?id=13ToB6s9MlDtDz2wbt2TxPxcNxzDrmTep"
# gdown.download(url, "events_LHCO2020_backgroundMC_Pythia.h5", quiet=False, )

# fn_signal1= r"processed_data/events_LHCO2020_BlackBox1.h5"
# url_signal1="https://drive.google.com/uc?export=download&id=1jeAtx6V7R-VfDQMwgQUt5GCbPjDbVc8w"
# gdown.download(url_signal1, fn_signal1, quiet=False)

# fn_signal2= r"processed_data/events_LHCO2020_BlackBox3.h5"
# url_signal2="https://drive.google.com/uc?export=download&id=1vOwsAvnZTC6XFCLbvUBwJWRyAtNZSLMx"
# gdown.download(url_signal2, fn_signal2, quiet=False)

"""## Download per noi: lavoriamo nella cartella "set dati machine learning"
Il dataset viene salvato nella cartella set dati machine learning/processed_data
"""

from google.colab import drive
import os
drive.mount('/content/drive')
os.makedirs('/content/drive/MyDrive/set dati machine learning/processed_data', exist_ok=True)
os.chdir('/content/drive/MyDrive/set dati machine learning')

"""### Use of google download  to download all the 3 file.h5 and file of masterkeys"""

import gdown
fn_back=r"processed_data/events_LHCO2020_backgroundMC_Pythia.h5"
url = "https://drive.google.com/uc?id=13ToB6s9MlDtDz2wbt2TxPxcNxzDrmTep"
if not os.path.exists(fn_back):
  gdown.download(url, fn_back, quiet=False)

fn_signal1= r"processed_data/events_LHCO2020_BlackBox1.h5"
url_signal1="https://drive.google.com/uc?export=download&id=1jeAtx6V7R-VfDQMwgQUt5GCbPjDbVc8w"
if not os.path.exists(fn_signal1):
  gdown.download(url_signal1, fn_signal1, quiet=False)
fn_signal1_m= r"processed_data/events_LHCO2020_BlackBox1.masterkey"
url_signal1_masterkey="https://drive.google.com/uc?export=download&id=1T_60d_IYZqWA4JDAmoVhVVzn2z1cqHHd"
if not os.path.exists(fn_signal1_m):
  gdown.download(url_signal1_masterkey, fn_signal1_m, quiet=False)

#fn_signal2= r"processed_data/events_LHCO2020_BlackBox3.h5"
#url_signal2="https://drive.google.com/uc?export=download&id=1vOwsAvnZTC6XFCLbvUBwJWRyAtNZSLMx"
#if not os.path.exists(fn_signal2):
#  gdown.download(url_signal2, fn_signal2, quiet=False)
#fn_signal2_m= r"processed_data/events_LHCO2020_BlackBox3.masterkey"
#url_signal2_masterkey="https://drive.google.com/uc?export=download&id=1I039ZBBlUWNGeQxrcDru3gTGcT4wvRz8"
#if not os.path.exists(fn_signal2_m):
#  gdown.download(url_signal2_masterkey, fn_signal2_m, quiet=False)

"""# Apertura con pandas e conversione in numpy"""

import pandas as pd
import numpy as np

N_back = 50000 #100000
N_signal = 50000 #20000

# Tabelle (df) di pandas - Il tuo codice originale
df_background = pd.read_hdf(fn_back, stop=N_back)
print(df_background.shape)
df_signal1 = pd.read_hdf(fn_signal1, stop=N_signal)
print(df_signal1.shape)

# --- AGGIUNTA DELLA MASTERKEY IN PANDAS ---
# Usiamo sep=r'\s+' (equivalente moderno di delim_whitespace)
# Usiamo nrows=N_signal per caricare lo stesso numero esatto di righe
df_signal1_m = pd.read_csv(fn_signal1_m, header=None, sep=r'\s+', nrows=N_signal)
print(df_signal1_m.shape)

# .values converts the DataFrame to a NumPy array
X_bg = df_background.values
X_test = df_signal1.values

# Estraiamo i valori della masterkey (colonna indice 0 perché ha una colonna sola)
Y_test = df_signal1_m.iloc[:, 0].values

print(type(X_bg), X_bg.shape)
print(type(Y_test), Y_test.shape)


true_labels_full = np.loadtxt('processed_data/events_LHCO2020_BlackBox1.masterkey')
print(true_labels_full.shape)

#@title Plot of 1 event with mask filter
import plotly.express as px

# 1. Prendi l'evento e rimuovi lo zero-padding
# Assumiamo X_bg[0] sia la riga del dataset
event = X_bg[0].reshape(-1, 3)
mask = event[:, 0] > 0  # Prende solo particelle con pT > 0
clean_event = event[mask]

# 2. Estrazione coordinate (pT, eta, phi)
pt = clean_event[:, 0]
eta = clean_event[:, 1]
phi = clean_event[:, 2]

# 3. Conversione in componenti cartesiane per il plot 3D
px_coords = pt * np.cos(phi)
py_coords = pt * np.sin(phi)
pz_coords = pt * np.sinh(eta)
fig = px.scatter_3d(
    x=px_coords, y=py_coords, z=pz_coords,
    # color=pt,  # Colora in base al pT per vedere i "core" dei jet
    labels={'x':'px (GeV)', 'y':'py (GeV)', 'z':'pz (GeV)', 'color':'pT'},
    title="Visualizzazione Evento LHCO (Particelle PF)",
    opacity=0.7,
    width=800, height=600
)

fig.update_traces(marker=dict(size=3))
fig.show()

"""# PER MARGHERITA,
IO METTEREI QUA IL CODICE PER CREARE IL DATASET DI TEST CON UNA SOGLIA PIU ALTA DI ANOMALIE, FORSE METTEREI UN 10% DEL TOTALE. FAREI FARE UN CHECK SE NEL DRIVE GIA ESISTE UN FILE (MAGARI CON ESTENSIONE .H5 OPPURE .NPY, MAGARI USANDO LA FUNZIONE COME SOPRA, if not os.path.exists("processed_data/new_test_dataset.h5")), E SE NON ESISTE ALLORA CREEREI  IL DATASET RIDOTTO es new_test_dataset.h5
UNA VOLTA CREATO, FAREI FARE UN LOAD USANdO SEMPRE QUALCOSA DI QUESTO TIPO:

df_signal1 = pd.read_hdf(
  r"new_test_dataset.h5"
  , stop=N_signal)
X_test = df_signal1.values

La stessa cosa dovrebbe essere fatta per
**processed_data/events_LHCO2020_BlackBox1.masterkey**


true_labels_full = np.loadtxt('processed_data/events_LHCO2020_BlackBox1_new.masterkey')
print(true_labels_full.shape)
"""

import os
import pandas as pd
import numpy as np

N_back = 50000
N_signal_mix = 20000     # I primi N eventi presi "alla cieca" dalla Black Box
CHUNK_SIZE = 10000       # Dimensione del blocco per la lettura successiva
TARGET_EXTRA_ANOMALIES = 900  # Quante anomalie extra vogliamo estrarre dal resto del file

# -------------------------------------------------------------------------
# 1. TRAINING SET: Solo Background puro
# -------------------------------------------------------------------------
df_background = pd.read_hdf(fn_back, stop=N_back)
X_train = df_background.values
print(f"X_train (Background puro) shape: {X_train.shape}")

# -------------------------------------------------------------------------
# 2. TEST SET - PARTE 1: I primi 20.000 eventi della Black Box (Mix reale)
# -------------------------------------------------------------------------
print(f"\nCaricamento dei primi {N_signal_mix} eventi da Black Box...")
df_sig_mix = pd.read_hdf(fn_signal1, stop=N_signal_mix)
df_m_mix = pd.read_csv(fn_signal1_m, header=None, sep=r'\s+', nrows=N_signal_mix)

X_test_mix = df_sig_mix.values
Y_test_mix = df_m_mix.iloc[:, 0].values

print(f"Mix iniziale caricato: X_test_mix {X_test_mix.shape} | Y_test_mix {Y_test_mix.shape}")
print(f"Anomalie già presenti in questo mix: {np.sum(Y_test_mix == 1)}")

# -------------------------------------------------------------------------
# 3. TEST SET - PARTE 2: Estrazione a blocchi di sole anomalie extra
# -------------------------------------------------------------------------
anomalies_features = []
anomalies_labels = []
total_anomalies_found = 0

# Partiamo a leggere dal punto in cui ci eravamo fermati (riga N_signal_mix)
current_row = N_signal_mix

print(f"\nInizio lettura a blocchi a partire dalla riga {current_row} per estrarre anomalie extra...")

while total_anomalies_found < TARGET_EXTRA_ANOMALIES:
    try:
        # Leggi il blocco di masterkey
        df_m_chunk = pd.read_csv(fn_signal1_m, header=None, sep=r'\s+',
                                 skiprows=current_row, nrows=CHUNK_SIZE)

        if df_m_chunk.empty:
            print("Fine del file raggiunta.")
            break

        # Leggi lo stesso blocco di feature
        df_sig_chunk = pd.read_hdf(fn_signal1, start=current_row, stop=current_row + len(df_m_chunk))

        # Filtra solo dove la masterkey dice che è un'anomalia (1)
        is_anomaly = (df_m_chunk.iloc[:, 0] == 1).values

        chunk_anomalies_X = df_sig_chunk[is_anomaly].values
        chunk_anomalies_Y = df_m_chunk[is_anomaly].iloc[:, 0].values

        if len(chunk_anomalies_X) > 0:
            # Controllo per non superare il target prefissato
            if total_anomalies_found + len(chunk_anomalies_X) > TARGET_EXTRA_ANOMALIES:
                needed = TARGET_EXTRA_ANOMALIES - total_anomalies_found
                chunk_anomalies_X = chunk_anomalies_X[:needed]
                chunk_anomalies_Y = chunk_anomalies_Y[:needed]

            anomalies_features.append(chunk_anomalies_X)
            anomalies_labels.append(chunk_anomalies_Y)
            total_anomalies_found += len(chunk_anomalies_X)

        print(f"Righe esaminate: {current_row + len(df_m_chunk)} | Anomalie extra trovate: {total_anomalies_found}/{TARGET_EXTRA_ANOMALIES}")

        current_row += len(df_m_chunk)

    except Exception as e:
        print(f"Interruzione lettura: {e}")
        break

# Concatena le anomalie extra trovate
if anomalies_features:
    X_extra_anomalies = np.vstack(anomalies_features)
    Y_extra_anomalies = np.concatenate(anomalies_labels)
else:
    X_extra_anomalies = np.empty((0, X_train.shape[1]))
    Y_extra_anomalies = np.empty((0,))

# -------------------------------------------------------------------------
# 4. CREAZIONE DEL TEST SET FINALE
# -------------------------------------------------------------------------
# Uniamo il mix iniziale dei primi 20k eventi con le anomalie extra filtrate successivamente
X_test = np.vstack([X_test_mix, X_extra_anomalies])
Y_test = np.concatenate([Y_test_mix, Y_extra_anomalies])

print("\n--- DATASET PRONTI PER L'AUTOENCODER ---")
print(f"X_train (Solo Background puro per training): {X_train.shape}")
print(f"X_test  (Primi 20k di Signal + Anomalie extra): {X_test.shape}")
print(f"Y_test  (Labels per la validazione/ROC): {Y_test.shape}")
print(f"Totale anomalie nel Test Set: {np.sum(Y_test == 1)} su {len(Y_test)} eventi totali.")

"""# 1) Preprocessing:
Codice sostanziale **finito!**
Potrebbe essere aggiunto, con **titolo Analysis 5 or 6**:
1.   Plot di un jet, magari lo stesso di sopra
2.   Usare gli array **GIA CREATI** (OVVERO "np_leading_jets" con le coordinate dei jet, "np_j1", con le coordinate delle particelle per ogni evento (ogni evento ha un solo jet, soglia a 50 particelle)) per verificare che tutti i nostri jet soddisfano una certa soglia di massa invariante


Il paper dice:(In order to emulate the effect of a typical LHC
online event selection, only jet pairs with invariant mass
mjj > 1260 GeV are considered.)



"""

#@title Download of Fastjet library to clusterize the particles in jets
!pip install fastjet

import fastjet
# import awkward as ak  #Awkward Array
# import vector
import matplotlib.pyplot as plt

#@title Kinematic function
def kinematic(j):
    """
    Input: j is an array:
    j[:,0] -> pT
    j[:,1] -> eta
    j[:,2] -> phi
    """
    # Spatial compontents
    px = j[:, 0] * np.cos(j[:, 2])
    py = j[:, 0] * np.sin(j[:, 2])
    pz = j[:, 0] * np.sinh(j[:, 1])

    # Energy, assuming massless particles
    # E = pT * cosh(eta)
    energy = j[:, 0] * np.cosh(j[:, 1])

    return px, py, pz, energy

#@title Anti-kT function to select energetic jet
def antikT(X_data, R=1.0, pt_min=1200.0, max_constituents=50):
    N_events = len(X_data)
    # Prepariamo gli array di output: (N, 3) per i jet, (N, 100, 3) per i costituenti
    out_jets = []
    out_constits = []
    out_num_of_constits=[]

    jetdef = fastjet.JetDefinition(fastjet.antikt_algorithm, R)

    for i in range(N_events):
        # 1. Reshape e pulizia
        event = X_data[i].reshape(700, 3)
        mask = event[:, 0] > 0
        p_reali = event[mask]

        # 2. Creazione PseudoJets
        px,py,pz,e=kinematic(p_reali)

        pjet_list = [fastjet.PseudoJet(x, y, z, en) for x, y, z, en in zip(px, py, pz, e)]

        # 3. Clustering
        cluster = fastjet.ClusterSequence(pjet_list, jetdef)
        # Filtriamo per ptmin e anche per |eta| < 2.5 come richiesto dal challenge
        jets = cluster.inclusive_jets(pt_min)
        jets = [j for j in jets if abs(j.eta()) < 2.5]

        if len(jets) > 0:
            # Ordiniamo per pT e prendiamo il leading
            jets = sorted(jets, key=lambda x: x.pt(), reverse=True)
            lead_j = jets[0]
            consts = lead_j.constituents()
            consts = sorted(consts, key=lambda x: x.pt(), reverse=True)

            # Salviamo il jet (pt, eta, phi)
            out_jets.append([lead_j.pt(), lead_j.eta(), lead_j.phi_std()])

            # 4. Estrazione costituenti con PADDING a 100
            c_list = []
            for j in range(max_constituents):
                if j < len(consts):
                    c = consts[j]
                    c_list.append([c.pt(), c.eta(), c.phi_std()])
                else:
                    c_list.append([0.0, 0.0, 0.0]) # Padding
            out_constits.append(c_list)
            out_num_of_constits.append(len(consts))

            # Stampa di progressione
            # if i % 1000 == 0:
            #     print(f"Evento (ne stampo 1 ogni 1000) {i}: Jet pT={lead_j.pt():.1f}, Costituenti={len(consts)}")
        else:
            # Se l'evento non ha jet validi, potresti volerlo saltare o mettere zeri
            continue

    return np.array(out_jets), np.array(out_constits), np.array(out_num_of_constits)

#@title Centering function (only for real particles, not for zero-padding ones)
def center_single_jet(jet_axis, constituents):
    """
    Centra i costituenti di un singolo jet rispetto al suo asse.

    Parametri:
    ----------
    jet_axis : np.array di shape (N, 3)
               Contiene [pt, eta, phi] del jet per ogni evento.
    constituents : np.array di shape (N, max_particles, 3)
                   Contiene [pt, eta, phi] dei costituenti.

    Ritorna:
    --------
    centered_constits : np.array (N, max_particles, 3) con eta e phi traslati.
    """
    # Copia dei dati per evitare side-effects
    centered_constits = np.copy(constituents)

    # 1. Estrazione coordinate del centro (espandiamo a (N, 1) per il broadcast)
    eta_jet = jet_axis[:, 1][:, np.newaxis]
    phi_jet = jet_axis[:, 2][:, np.newaxis]

    # 2. Maschera di validità: identifichiamo dove pt > 0 (escludiamo il padding)
    mask_real = centered_constits[:, :, 0] > 0

    # 3. Calcolo Delta Eta
    centered_constits[:, :, 1] = (centered_constits[:, :, 1] - eta_jet) * mask_real

    # 4. Calcolo Delta Phi con correzione periodica (range [-pi, pi])
    d_phi = centered_constits[:, :, 2] - phi_jet
    d_phi = (d_phi + np.pi) % (2 * np.pi) - np.pi
    centered_constits[:, :, 2] = d_phi * mask_real

    return centered_constits

max_constituents=50

"""### background dataset: jet clustering and centering"""

np_leading_jets, np_j1, np_numberofparticles = antikT(X_bg, max_constituents=max_constituents)
print(np_leading_jets.shape, np_j1.shape,  np_numberofparticles.shape)
#pd.DataFrame(np_j1[1,]).head() #rimuovere a fine lavori

"""$(\eta, \phi) \xrightarrow{} (\Delta \eta, \Delta \phi)$  """

j1_background = center_single_jet(np_leading_jets,  np_j1)
print(j1_background.shape)

"""### test dataset: jet clustering and centering"""

np_leading_jets_test, np_j1_test, np_numberofparticles_test = antikT(X_test,  max_constituents=max_constituents)
print(np_leading_jets_test.shape, np_j1_test.shape, np_numberofparticles_test.shape)

#@title Plot of 1 event with cluster
d = X_bg[0].reshape(-1, 3)
j=np_j1[0].reshape(-1,3)
print(j.shape)
print(d.shape)


# Calculate p_x, p_y, p_z for original event particles (d)
p_x_d, p_y_d, p_z_d, e_d = kinematic(d)

# Calculate p_x, p_y, p_z for jet constituents (j)
p_x_j, p_y_j, p_z_j, e_j=kinematic(j)

# Create DataFrames for plotting
df_d = pd.DataFrame({
    'px': p_x_d,
    'py': p_y_d,
    'pz': p_z_d,
    'type': 'Original Event Particles'
})

df_j = pd.DataFrame({
    'px': p_x_j,
    'py': p_y_j,
    'pz': p_z_j,
    'type': 'Jet Constituents'
})

# Concatenate the DataFrames
combined_df = pd.concat([df_d, df_j])

# Plot interattivo con colori diversi
fig = px.scatter_3d(
    combined_df,
    x='px', y='py', z='pz',
    color='type', # Use the 'type' column for coloring
    color_discrete_map={
        'Original Event Particles': 'blue',
        'Leading jet': 'red'
    },
    labels={'px':'px', 'py':'py', 'pz':'pz'},
    opacity=0.7, # Adjusted opacity for better visibility
    width=500, # Slightly increased width
    height=400, # Increased height for better 3D view
    title='Original Event Particles vs. Jet Constituents' # Added a title
)
fig.update_traces(marker=dict(size=4))
fig.show()

"""$(\eta, \phi) \xrightarrow{} (\Delta \eta, \Delta \phi)$  """

j1_test = center_single_jet(np_leading_jets_test,  np_j1_test)
print(j1_test.shape)

"""## Scaling"""

#@title Scaling: Standard Scaling for phi and heta, MaxAbsScaling for pT
from sklearn.preprocessing import StandardScaler

X_bg_reshaped = j1_background.reshape(-1, 3).copy()
X_test_reshaped = j1_test.reshape(-1, 3).copy()


X_bg_reshaped[:, 0] = np.log1p(X_bg_reshaped[:, 0])
X_test_reshaped[:, 0] = np.log1p(X_test_reshaped[:, 0])

# Use of Standard Scaler
scaler = StandardScaler()

X_bg_scaled = scaler.fit_transform(X_bg_reshaped)
X_test_scaled = scaler.transform(X_test_reshaped)

# Original Shape
j1_background_scaled = X_bg_scaled.reshape(j1_background.shape)
j1_test_scaled = X_test_scaled.reshape(j1_test.shape)

print("Normalization using StandardScaler:")

print(f"---> Final dimensions: background {j1_background_scaled.shape}, test {j1_test_scaled.shape}")

"""## Analize the dataset:"""

#@title Analysis 1: number of costituents optimal
plt.figure(figsize=(5, 3))
plt.title("Histogram of number of constituents")
plt.xlabel("Number of Constituents")
plt.ylabel("Events")
plt.hist(np_numberofparticles, bins=20, color='blue', alpha=0.7, edgecolor='black', label=f"Background (mean: {int(np_numberofparticles.mean())}, min: {min(np_numberofparticles)})")
plt.hist(np_numberofparticles_test, bins=20, color='red', alpha=0.7, edgecolor='black', label=f"Test (mean: {int(np_numberofparticles_test.mean())}, min: {min(np_numberofparticles_test)})")
plt.axvline(x=max_constituents, color='black', linestyle='--', label=f"Threshold {max_constituents}")
plt.legend(), plt.grid(),
plt.show()

#@title Analysis 2: distribution of pT, heta, phi before centering
plt.figure(figsize=(7, 9))
plt.subplot(4, 1, 1)
plt.title("Distribution of pT")
plt.xlabel("pT [GeV]")
plt.ylabel("Density of Events")
# .ravel() is like flatten
plt.hist(np_j1[:, :, 0].ravel(), bins=50, color='blue', alpha=0.5, edgecolor='black',
         label=f"Background (mean: {np_j1[:, :, 0].mean():.1f})", density=True)
plt.hist(np_j1_test[:, :, 0].ravel(), bins=50, color='red', alpha=0.5, edgecolor='black',
         label=f"Test (mean: {np_j1_test[:, :, 0].mean():.1f})", density=True)
plt.legend(), plt.grid()

plt.subplot(4, 1, 2)
plt.title("Distribution of log(pT+1)")
plt.xlabel("log(pT+1)")
plt.ylabel("Density of Events")
log_bg= np.log1p(np_j1[:,:,0].ravel())
log_test= np.log1p(np_j1_test[:,:,0].ravel())
plt.hist(log_bg, bins=50, color='blue', alpha=0.5, label=f"BG (mean: {log_bg.mean():.1f})", density=True)
plt.hist(log_test, bins=50, color='red', alpha=0.5, label=f"Test (mean: {log_test.mean():.1f})", density=True)
plt.legend(), plt.grid()

plt.subplot(4, 1, 3)
plt.title("Distribution of heta")
plt.xlabel("heta")
plt.ylabel("Density of Events")
plt.hist(np_j1[:, :,1].ravel(), bins=30, color='blue', alpha=0.5, edgecolor='black',
         label=f"Background (mean: {np_j1[:, :,1].mean():.1f})", density=True)
plt.hist(np_j1_test[:, :,1].ravel(), bins=30, color='red', alpha=0.5, edgecolor='black',
         label=f"Test (mean: {np_j1_test[:, :,1].mean():.1f})", density=True)
plt.legend(), plt.grid()

plt.subplot(4, 1, 4)
plt.title("Distribution of phi")
plt.xlabel("phi")
plt.ylabel("Density of Events")
plt.hist(np_j1[:, :, 2].ravel(), bins=30, color='blue', alpha=0.5, edgecolor='black',
         label=f"Background (mean: {np_j1[:, :, 2].mean():.1f})", density=True)
plt.hist(np_j1_test[:, :, 2].ravel(), bins=30, color='red', alpha=0.5, edgecolor='black',
         label=f"Test (mean: {np_j1_test[:, :, 2].mean():.1f})", density=True)
plt.legend(), plt.grid()

plt.tight_layout()
plt.show()

#@title Analysis 3: distribution of eta, phi after centering
plt.figure(figsize=(7, 5))
plt.subplot(2, 1, 1)
plt.title("Distribution of heta")
plt.xlabel("heta")
plt.ylabel("Density of Events")
plt.hist(j1_background[:, :,1].ravel(), bins=30, color='blue', alpha=0.5, edgecolor='black',
         label=f"Background (mean: {j1_background[:, :,1].mean():.1f})", density=True)
plt.hist(j1_test[:, :,1].ravel(), bins=30, color='red', alpha=0.5, edgecolor='black',
         label=f"Test (mean: {j1_test[:, :,1].mean():.1f})", density=True)
plt.legend(), plt.grid()

plt.subplot(2, 1, 2)
plt.title("Distribution of phi")
plt.xlabel("phi")
plt.ylabel("Density of Events")
plt.hist(j1_background[:, :, 2].ravel(), bins=30, color='blue', alpha=0.5, edgecolor='black',
         label=f"Background (mean: {j1_background[:, :, 2].mean():.1f})", density=True)
plt.hist(j1_test[:, :, 2].ravel(), bins=30, color='red', alpha=0.5, edgecolor='black',
         label=f"Test (mean: {j1_test[:, :, 2].mean():.1f})", density=True)
plt.legend(), plt.grid()

plt.tight_layout()
plt.show()

#@title Analysis 4: distribution of pT, heta, phi after centering and scaling
plt.figure(figsize=(15, 4))
plt.subplot(1, 3, 1)
plt.title("Distribution of log1(pT)")
plt.xlabel("log1(pT)")
plt.ylabel("Density of Events")
# .ravel() is like flatten
plt.hist(j1_background_scaled[:, :, 0].ravel(), bins=50, color='blue', alpha=0.5, edgecolor='black',
         label=f"Background (mean: {j1_background_scaled[:, :, 0].mean():.1f})", density=True)
plt.hist(j1_test_scaled[:, :, 0].ravel(), bins=50, color='red', alpha=0.5, edgecolor='black',
         label=f"Test (mean: {j1_test_scaled[:, :, 0].mean():.1f})", density=True)

plt.legend(), plt.grid()

plt.subplot(1, 3, 2)
plt.title("Distribution of heta")
plt.xlabel("heta")
plt.ylabel("Density of Events")
plt.hist(j1_background_scaled[:, :,1].ravel(), bins=30, color='blue', alpha=0.5, edgecolor='black',
         label=f"Background (mean: {j1_background_scaled[:, :,1].mean():.1f})", density=True)
plt.hist(j1_test_scaled[:, :,1].ravel(), bins=30, color='red', alpha=0.5, edgecolor='black',
         label=f"Test (mean: {j1_test_scaled[:, :,1].mean():.1f})", density=True)
plt.legend(), plt.grid()

plt.subplot(1, 3, 3)
plt.title("Distribution of phi")
plt.xlabel("phi")
plt.ylabel("Density of Events")
plt.hist(j1_background_scaled[:, :, 2].ravel(), bins=30, color='blue', alpha=0.5, edgecolor='black',
         label=f"Background (mean: {j1_background_scaled[:, :, 2].mean():.1f})", density=True)
plt.hist(j1_test_scaled[:, :, 2].ravel(), bins=30, color='red', alpha=0.5, edgecolor='black',
         label=f"Test (mean: {j1_test_scaled[:, :, 2].mean():.1f})", density=True)
plt.legend(), plt.grid()

plt.tight_layout()
plt.show()

#@title Analysis 5: Check of invariant mass
def check_initial_mass(X_data):
    masses = []
    for i in range(len(X_data)):
        # Reshape dell'evento in particelle [pt, eta, phi]
        event = X_data[i].reshape(-1, 3)

        # Filtriamo le particelle "nulle" (padding)
        mask = event[:, 0] > 0
        p_reali = event[mask]

        if len(p_reali) == 0:
            continue

        # Calcolo componenti del quadri-momento usando la funzione sopra
        px, py, pz, e = kinematic(p_reali)

        # Somma dei quadri-momenti di tutte le particelle nell'evento
        E_tot = np.sum(e)
        Px_tot = np.sum(px)
        Py_tot = np.sum(py)
        Pz_tot = np.sum(pz)

        # Massa invariante: M^2 = E^2 - |P|^2
        m2 = E_tot**2 - (Px_tot**2 + Py_tot**2 + Pz_tot**2)

        # max(0, m2) evita problemi numerici con numeri piccolissimi negativi
        masses.append(np.sqrt(max(0, m2)))

    return np.array(masses)

# Esecuzione (Assicurati che j1_background sia definito)
m_iniziali = check_initial_mass(np_j1)

# Visualizzazione
plt.figure(figsize=(6, 3))
plt.hist(m_iniziali, bins=100, color='royalblue', alpha=0.7, edgecolor='black')
plt.axvline(1260, color='red', linestyle='--', linewidth=2, label='Soglia articolo (1260 GeV)')

plt.title("Distribuzione della Massa Invariante Totale", fontsize=14)
plt.xlabel("Massa [GeV]", fontsize=12)
plt.ylabel("Numero di Eventi", fontsize=12)
plt.yscale('log')
plt.grid(axis='y', alpha=0.3)
plt.legend()
plt.show()

if len(m_iniziali) > 0:
    print(f"Statistiche della massa:")
    print(f"- Minima: {m_iniziali.min():.2f} GeV")
    print(f"- Massima: {m_iniziali.max():.2f} GeV")
    print(f"- Media: {m_iniziali.mean():.2f} GeV")

"""## Creation of torch-tensor and DataLoaders:"""

#@title Torch DataLoader
import torch
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split

# Split 70% Train - 30% Validation
X_train, X_val = train_test_split(j1_background_scaled, test_size=0.30, random_state=42)

# Conversion in PyTorch
tensor_X_train = torch.tensor(X_train, dtype=torch.float32)
tensor_X_val = torch.tensor(X_val, dtype=torch.float32)

# TensorDataset (Input, Target) -> Autoencoder input is (X, X)
train_dataset = TensorDataset(tensor_X_train, tensor_X_train)
val_dataset = TensorDataset(tensor_X_val, tensor_X_val)

# Creation of DataLoader
#@markdown Change of Batch_size by Luca, set to 64 as was in my code
#@markdown Se avete tempo, potete provare ad aumentare o diminuire e vedere come va il learning, confrontando tempo e performance
batch_size = 64 #@param {"type": "integer"}
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

# Test dataset
tensor_X_test = torch.tensor(j1_test_scaled, dtype=torch.float32)
test_dataset = TensorDataset(tensor_X_test, tensor_X_test)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

print(f"Number of Batches for Train Loader:{len(train_loader)}")
print(f"Number of Batches for Val Loader: {len(val_loader)}")
print(f"Number of Batches for Test Loader (BlackBox): {len(test_loader)}")

#@title Prove of one element of the loaders
elem, elem = next(iter(train_loader))
print(elem.shape, end=" ")
elem, elem = next(iter(test_loader))
print(elem.shape, end=" ")
elem, elem = next(iter(val_loader))
print(elem.shape)

"""# 2) Autoencoder:
tutto l'autoencoder è ok, per favore non modificarlo, al più modificare i parametri che compaiono, oppure modificare la loss
"""

import torch
import torch.nn as nn
from torchsummary import summary
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device is: ", device)

#@title Modello di John vecchio, io Luca lo ho commentato ma non cancellato, vedete voi, se approvate lo leviamo
#Modello con parametri aumentati (fix factor dinamico)
# import torch
# import torch.nn as nn
# from torchsummary import summary

# class Encoder(nn.Module):

#     def __init__(
#         self,
#         hidden_dim=12,
#         num_features=3,
#         latent_dim=8,
#         kernel1d=5,
#         padd1d=2,
#         max_constituents=max_constituents
#     ):
#         super(Encoder, self).__init__()
#         self.hidden_dim = hidden_dim
#         self.max_constituents = max_constituents

#         self.conv2d = nn.Conv2d(
#             in_channels=1,
#             out_channels=hidden_dim,
#             kernel_size=(1, num_features)
#         )
#         self.input_activation = nn.LeakyReLU(0.2)

#         self.encoder_cnn = nn.Sequential(
#             # MIGLIORAMENTO 1: Conv1d kernel=1
#             nn.Conv1d(hidden_dim, hidden_dim, kernel_size=1),
#             nn.GroupNorm(1, hidden_dim),
#             nn.LeakyReLU(0.2),

#             nn.Conv1d(hidden_dim, hidden_dim * 2, kernel_size=kernel1d, padding=padd1d),
#             nn.GroupNorm(1, hidden_dim * 2),
#             nn.LeakyReLU(0.2),
#             nn.MaxPool1d(kernel_size=2, ceil_mode=True),

#             nn.Conv1d(hidden_dim * 2, hidden_dim * 3, kernel_size=kernel1d, padding=padd1d),
#             nn.GroupNorm(1, hidden_dim * 3),
#             nn.LeakyReLU(0.2),
#             nn.MaxPool1d(kernel_size=2, ceil_mode=True),
#         )

#         # FIX: calcolo factor dinamicamente invece di hardcodare 13
#         # così funziona con qualsiasi kernel1d/padd1d
#         import math
#         after_pool1 = math.ceil(max_constituents / 2)
#         after_pool2 = math.ceil(after_pool1 / 2)
#         self.factor = after_pool2

#         self.encoder_linear = nn.Sequential(
#             nn.Linear(hidden_dim * 3 * self.factor, hidden_dim * 2),
#             nn.LayerNorm(hidden_dim * 2),
#             nn.LeakyReLU(0.2),

#             nn.Linear(hidden_dim * 2, hidden_dim),
#             nn.LayerNorm(hidden_dim),
#             nn.LeakyReLU(0.2),

#             nn.Linear(hidden_dim, latent_dim)
#         )

#     def forward(self, x):
#         x = x.unsqueeze(1)
#         x = self.conv2d(x)
#         x = self.input_activation(x)
#         x = x.squeeze(-1)
#         x = self.encoder_cnn(x)
#         x = x.flatten(1)
#         x = self.encoder_linear(x)
#         return x



# class Decoder(nn.Module):

#     def __init__(
#         self,
#         hidden_dim=12,
#         num_features=3,
#         latent_dim=8,
#         kernel1d=5,
#         padd1d=2,
#         max_constituents=max_constituents
#     ):
#         super(Decoder, self).__init__()
#         self.hidden_dim = hidden_dim
#         self.num_features = num_features
#         self.max_constituents = max_constituents

#         # FIX: stesso calcolo dinamico del factor
#         import math
#         after_pool1 = math.ceil(max_constituents / 2)
#         after_pool2 = math.ceil(after_pool1 / 2)
#         self.factor = after_pool2

#         self.decoder_linear = nn.Sequential(
#             nn.Linear(latent_dim, hidden_dim),
#             nn.LayerNorm(hidden_dim),
#             nn.LeakyReLU(0.2),

#             nn.Linear(hidden_dim, hidden_dim * 2),
#             nn.LayerNorm(hidden_dim * 2),
#             nn.LeakyReLU(0.2),

#             nn.Linear(hidden_dim * 2, hidden_dim * 3 * self.factor),
#             nn.LayerNorm(hidden_dim * 3 * self.factor),
#             nn.LeakyReLU(0.2)
#         )

#         self.decoder_cnn = nn.Sequential(
#             nn.Upsample(scale_factor=2),
#             nn.ConvTranspose1d(hidden_dim * 3, hidden_dim * 2, kernel_size=kernel1d, padding=padd1d),
#             nn.GroupNorm(1, hidden_dim * 2),
#             nn.LeakyReLU(0.2),

#             nn.Upsample(scale_factor=2),
#             nn.ConvTranspose1d(hidden_dim * 2, hidden_dim, kernel_size=kernel1d, padding=padd1d),
#             nn.GroupNorm(1, hidden_dim),
#             nn.LeakyReLU(0.2)
#         )

#         self.conv2d_transpose = nn.ConvTranspose2d(
#             hidden_dim, 1, kernel_size=(1, num_features)
#         )

#     def forward(self, x):
#         x = self.decoder_linear(x)
#         x = x.view(-1, self.hidden_dim * 3, self.factor)
#         x = self.decoder_cnn(x)
#         x = x.unsqueeze(-1)
#         x = self.conv2d_transpose(x)
#         x = x.squeeze(1)
#         x = x[:, :self.max_constituents, :]
#         return x


# class DeepConvAutoencoder(nn.Module):

#     def __init__(
#         self,
#         num_features=3,
#         latent_dim=16,
#         hidden_dim=64,
#         kernel1d=7,
#         padd1d=2,
#         max_constituents=max_constituents
#     ):
#         super(DeepConvAutoencoder, self).__init__()
#         self.encoder = Encoder(hidden_dim, num_features, latent_dim, kernel1d, padd1d, max_constituents)
#         self.decoder = Decoder(hidden_dim, num_features, latent_dim, kernel1d, padd1d, max_constituents)

#     def forward(self, x):
#         return self.decoder(self.encoder(x))

#     def get_latent(self, x):
#         return self.encoder(x)


# # Istanziazione con parametri aumentati
# lat_dim = 8  # NON si tocca

# model = DeepConvAutoencoder(
#     num_features=3,
#     latent_dim=lat_dim,
#     hidden_dim=128,   # era 64
#     kernel1d=7,       # era 5
#     padd1d=3,         # kernel1d // 2
#     max_constituents=max_constituents
# ).to(device)

# print(f"factor calcolato: {model.encoder.factor}")  # deve stampare 13
# print(f"Parametri totali: {sum(p.numel() for p in model.parameters()):,}")

# if torch.cuda.is_available():
#     summary(model.cuda(), (max_constituents, 3))
# else:
#     summary(model, input_size=(max_constituents, 3))
# #print(f\"Model Multi-layer CNN created on: {device}\")

"""## Model"""

#@title Encoder
class Encoder(nn.Module):
    def __init__(self, hidden_dim=12, num_features=3, latent_dim=8, kernel1d=5, padd1d=1, max_constituents=max_constituents):
        super(Encoder, self).__init__()
        self.conv2d=nn.Conv2d(in_channels=1, out_channels= hidden_dim, kernel_size=(1, num_features))
        self.act_2d=nn.LeakyReLU(0.2)
        self.encoder_cnn = nn.Sequential(
            nn.Conv1d(in_channels=hidden_dim, out_channels=hidden_dim*2, kernel_size=kernel1d, padding=padd1d),
            nn.BatchNorm1d(hidden_dim*2),
            nn.LeakyReLU(0.2),
            nn.MaxPool1d(kernel_size=2), # maxpool in 2dimension
            nn.Conv1d(in_channels=hidden_dim*2, out_channels=hidden_dim*3, kernel_size=kernel1d, padding=padd1d),
            nn.BatchNorm1d(hidden_dim*3),
            nn.LeakyReLU(0.2),
            nn.MaxPool1d(kernel_size=2), # maxpool in 2dimension
        )

        #factor is a dynamic value of the last layer, before the flatten function
        self.factor= ((((max_constituents + 2*padd1d - kernel1d) // 1 + 1) // 2 + 2*padd1d - kernel1d) // 1 + 1) // 2

        self.encoder_linear = nn.Sequential(
            nn.Linear(hidden_dim*3 * self.factor, hidden_dim*2),
            nn.BatchNorm1d(hidden_dim*2),
            nn.LeakyReLU(0.2),
            nn.Linear(hidden_dim*2, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.LeakyReLU(0.2),
            nn.Linear(hidden_dim, latent_dim),
            #tangh
            nn.Tanh()
        )

    def forward(self, x):
        x = self.conv2d(x.unsqueeze(1))
        x = self.act_2d(x)
        x = x.squeeze(-1)
        x = self.encoder_cnn(x)
        x = x.flatten(1)
        x= self.encoder_linear(x)
        return x

# Visualizzazione riassunto Encoder
# print("--- SUMMARY ENCODER ---")
# encoder_test = Encoder().to(device)
# if torch.cuda.is_available():
#   summary(encoder_test.cuda(), input_size=(max_constituents, 3))
# else:
#   summary(encoder_test, input_size=(max_constituents, 3))

#@title Decoder
class Decoder(nn.Module):
    def __init__(self, hidden_dim=12, num_features=3, latent_dim=8, kernel1d=5, padd1d=1, max_constituents=max_constituents):
        super(Decoder, self).__init__()
        self.hidden_dim = hidden_dim
        self.num_features = num_features


        self.s2 = (max_constituents + 2*padd1d - kernel1d) // 1 + 1  # Dim dopo Conv1
        self.s3 = self.s2 // 2                                       # Dim dopo Pool1
        self.s4 = (self.s3 + 2*padd1d - kernel1d) // 1 + 1          # Dim dopo Conv2
        self.factor = self.s4 // 2                                   # Dim dopo Pool2
        #LAYERS|
        self.decoder_linear = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.LeakyReLU(0.2),
            nn.Linear(hidden_dim, hidden_dim*2),
            nn.BatchNorm1d(hidden_dim*2),
            nn.LeakyReLU(0.2),
            nn.Linear(hidden_dim*2, hidden_dim*3 * self.factor),
            nn.BatchNorm1d(hidden_dim*3 * self.factor),
            nn.LeakyReLU(0.2)
        )

        self.decoder_cnn = nn.Sequential(
            nn.Upsample(size=self.s4),
            nn.ConvTranspose1d(hidden_dim*3, hidden_dim*2, kernel_size=kernel1d, padding=padd1d),
            nn.BatchNorm1d(hidden_dim*2),
            nn.LeakyReLU(0.2),
            nn.Upsample(size=self.s2),
            nn.ConvTranspose1d(hidden_dim*2, hidden_dim, kernel_size=kernel1d, padding=padd1d),
            nn.BatchNorm1d(hidden_dim),
            nn.LeakyReLU(0.2)
        )

        self.conv2d_transpose = nn.ConvTranspose2d(hidden_dim, 1, kernel_size=(1, num_features))

    def forward(self, x):
        x = self.decoder_linear(x)
        x = x.view(-1, self.hidden_dim*3, self.factor)
        x = self.decoder_cnn(x)
        x = x.unsqueeze(-1)
        x = self.conv2d_transpose(x)
        x= torch.tanh(x)*3
        return x.squeeze(1)

# print("--- SUMMARY DECODER ex---")
# decoder_test = Decoder(latent_dim=8, max_constituents=50).to(device)
# if torch.cuda.is_available():
#     summary(decoder_test.cuda(), input_size=(8,))
# else:
#     summary(decoder_test, input_size=(8,))

#@title DeepConvAutoencoder
lat_dim=8 #@param [4, 8, 16] {type:"raw"}
class DeepConvAutoencoder(nn.Module):
    def __init__(self, num_features=3, latent_dim=8, hidden_dim=12, kernel1d=5, padd1d=1, max_constituents=max_constituents):
        super(DeepConvAutoencoder, self).__init__()
        self.encoder = Encoder(hidden_dim, num_features, latent_dim, kernel1d, padd1d, max_constituents)
        self.decoder = Decoder(hidden_dim, num_features, latent_dim, kernel1d, padd1d, max_constituents)

    def forward(self, x):
        latent = self.encoder(x)
        reconstruction = self.decoder(latent)
        return reconstruction

    def get_latent(self, x):
        return self.encoder(x)


model = DeepConvAutoencoder(num_features=3,
                            latent_dim=lat_dim,
                            hidden_dim=12 #@param {"type": "integer"},
                            ,
                            kernel1d=3 #@param {"type":"integer"}
                            ,
                            padd1d=1 #@param {"type":"integer"}
                            ,
                            max_constituents=max_constituents).to(device)

print("--- SUMMARY AUTOENCODER COMPLETE ---")
if torch.cuda.is_available():
    summary(model.cuda(), (max_constituents, 3))
else:
    summary(model, input_size=(max_constituents, 3))
print(f"Model Multi-layer CNN created on: {device}")

"""## Training
*   Messo il salvataggio in automatico

### Chamfer Loss
$$L_R = \sum_{i \in \text{input}} \min_j \left[ (x^{(i)} - x^{(j)})^2 \right] + \sum_{j \in \text{output}} \min_i \left[ (x^{(j)} - x^{(i)})^2 \right] $$
"""

#@title Chamfer_loss definition

def chamfer_loss(a, b):
    """
    Computes the Chamfer Distance between two point clouds
    Assumes 'a' and 'b' have shapes [Batch_Size, Number_of_Points, Dimensions]
    or simply [Number_of_Points, Dimensions].
    """
    # If there is no batch dimension, add it for compatibility
    if len(a.shape) == 2:
        a = a.unsqueeze(0)
    if len(b.shape) == 2:
        b = b.unsqueeze(0)

    # Compute the squared distance matrix between all points
    # Formula: ||A - B||^2 = ||A||^2 + ||B||^2 - 2*A*B^T
    a_sq = torch.sum(a**2, dim=-1, keepdim=True) # [B, N, 1]
    b_sq = torch.sum(b**2, dim=-1, keepdim=True).transpose(-2, -1) # [B, 1, M]
    dist_matrix = a_sq + b_sq - 2 * torch.bmm(a, b.transpose(-2, -1)) # [B, N, M]

    # For each point in A, find the minimum distance to the closest point in B
    dist_a_to_b, _ = torch.min(dist_matrix, dim=-1) # [B, N]
    # For each point in B, find the minimum distance to the closest point in A
    dist_b_to_a, _ = torch.min(dist_matrix, dim=-2) # [B, M]

    # Average the distances for both directions and sum them up
    loss = torch.mean(dist_a_to_b) + torch.mean(dist_b_to_a)
    return loss

"""### Start Training"""

#@title train con Chamfer Loss without mask with good Learning scheduler
#@markdown Ho anche il training della Chamfer loss con mask, se vi serve ditemelo (Luca)
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau

load_saved_model = False #@param {type:"boolean"}
best_model_path = '/content/drive/MyDrive/set dati machine learning/best_autoencoder.pth'

criterion = chamfer_loss
epochs = 140   #@param {type:"slider", min:120, max:200, step:10}
patience_limit = 15 #@param {type:"slider",  min:5, max:15, step:1}


optimizer = optim.Adam(model.parameters(), lr=1e-3)
scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5)

if load_saved_model:
    model.load_state_dict(torch.load(best_model_path))
    print(f"MODEL LOADED: {best_model_path}")
else:
    print("NEW TRAINING STARTED")

    patience_counter = 0
    train_losses, val_losses = [], []
    # Variable useful to save the best model if best_val_loss decreases
    best_val_loss = float('inf')

    for epoch in range(epochs):
        model.train() # training mode
        running_train_loss = 0.0

        for batch_x, _ in train_loader:
            batch_x = batch_x.to(device)
            # Forward pass
            reconstructed = model(batch_x)
            loss = criterion(reconstructed, batch_x)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            running_train_loss += loss.item() * batch_x.size(0)
        # Compute mean loss of the epoch
        epoch_train_loss = running_train_loss / len(train_loader.dataset)
        train_losses.append(epoch_train_loss)

        # --- FASE VALIDATION ---
        model.eval()
        running_val_loss = 0.0
        with torch.no_grad():
            for batch_x, _ in val_loader:
                batch_x = batch_x.to(device)
                reconstructed = model(batch_x)
                loss = criterion(reconstructed, batch_x)
                running_val_loss += loss.item() * batch_x.size(0)

        epoch_val_loss = running_val_loss / len(val_loader.dataset)
        val_losses.append(epoch_val_loss)

        # --- EARLY STOPPING + SAVE ---
        if epoch_val_loss < best_val_loss:
            best_val_loss = epoch_val_loss
            torch.save(model.state_dict(), best_model_path)
            patience_counter = 0
            print(f"--> better model found! Model saved at: {epoch_val_loss:.4f}")
        else:
            patience_counter += 1
            if patience_counter >= patience_limit:
                print(f"Early stopping all'epoca {epoch+1} (val_loss ferma da {patience_limit} epoche)")
                break

        scheduler.step(epoch_val_loss)
        current_lr = optimizer.param_groups[0]['lr']
        if epoch % 2 == 0:
            print(f"Epoch [{epoch+1:2d}/{epochs}] | LR: {current_lr:.5f} | Train Loss: {epoch_train_loss:.4f} | Val Loss: {epoch_val_loss:.4f} | Patience: {patience_counter}/{patience_limit}")

    print(f"--> Weights saved in: {best_model_path}")

#@title Vecchio training e loss di John, lo tengo commentato se approvate lo leviamo
# import torch.optim as optim
# from torch.optim.lr_scheduler import ReduceLROnPlateau
# import matplotlib.pyplot as plt


# def weighted_masked_loss(recon, target):
#     mask = (target.abs().sum(dim=-1) > 0).float()
#     weights = torch.tensor([1.0, 3.0, 3.0], device=target.device)
#     loss_per_comp = ((recon - target) ** 2) * weights
#     loss_per_particle = loss_per_comp.sum(dim=-1)
#     loss_masked = (loss_per_particle * mask).sum() / (mask.sum() + 1e-8)
#     return loss_masked

# criterion = weighted_masked_loss
# optimizer = optim.Adam(model.parameters(), lr=0.001)
# scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5)

# epochs = 100         #@param {"type": "integer"}
# noise_factor = 0.05 #@param {"type": "number"}
# patience_limit = 15 #@param {"type": "integer"}

# train_losses = []
# val_losses = []
# best_val_loss = float('inf')
# patience_counter = 0
# best_model_path = '/content/drive/MyDrive/set dati machine learning/best_autoencoder.pth'

# print("\nStart Denoising AE training...\n")

# for epoch in range(epochs):
#     # --- TRAIN ---
#     model.train()
#     running_train_loss = 0.0
#     for batch_x, _ in train_loader:
#         batch_x = batch_x.to(device)

#         # MODIFICA 3: aggiungi rumore SOLO all'input, target rimane pulito
#         # la maschera evita di aggiungere rumore sulle particelle di padding
#         mask_3d = (batch_x.abs().sum(dim=-1, keepdim=True) > 0).float()
#         batch_x_noisy = batch_x + noise_factor * torch.randn_like(batch_x)
#         batch_x_noisy = batch_x_noisy * mask_3d

#         reconstructed = model(batch_x_noisy)           # input: rumoroso
#         loss = criterion(reconstructed, batch_x)  # target: pulito

#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()
#         running_train_loss += loss.item() * batch_x.size(0)

#     epoch_train_loss = running_train_loss / len(train_loader.dataset)
#     train_losses.append(epoch_train_loss)

#     # --- VALIDATION (senza rumore) ---
#     model.eval()
#     running_val_loss = 0.0
#     with torch.no_grad():
#         for batch_x, _ in val_loader:
#             batch_x = batch_x.to(device)
#             reconstructed = model(batch_x)
#             loss = weighted_masked_loss(reconstructed, batch_x)
#             running_val_loss += loss.item() * batch_x.size(0)

#     epoch_val_loss = running_val_loss / len(val_loader.dataset)
#     val_losses.append(epoch_val_loss)

#     # --- EARLY STOPPING + SAVE ---
#     if epoch_val_loss < best_val_loss:
#         best_val_loss = epoch_val_loss
#         torch.save(model.state_dict(), best_model_path)
#         patience_counter = 0
#     else:
#         patience_counter += 1
#         if patience_counter >= patience_limit:
#             print(f"Early stopping all'epoca {epoch+1} (val_loss ferma da {patience_limit} epoche)")
#             break

#     scheduler.step(epoch_val_loss)
#     current_lr = optimizer.param_groups[0]['lr']
#     print(
#         f"Epoch [{epoch+1:2d}/{epochs}] "
#         f"| LR: {current_lr:.5f} "
#         f"| Train Loss: {epoch_train_loss:.4f} "
#         f"| Val Loss: {epoch_val_loss:.4f} "
#         f"| Patience: {patience_counter}/{patience_limit}"
#     )

#@title plot loss

plt.figure(figsize=(10, 4))
plt.plot(range(1, len(train_losses)+1), train_losses, label='Training Loss', linewidth=2)
plt.plot(range(1, len(val_losses)+1), val_losses, label='Validation Loss', linewidth=2)
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Loss', fontsize=12)
plt.yscale('log')
plt.title('Denoising AE - Curve di apprendimento', fontsize=14)
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""## Analisi spazio latente:"""

#@title Analysis Latent Space
import matplotlib.pyplot as plt
import numpy as np
import torch

model.eval()
#Use of a batch to do plots
sample_data, _ = next(iter(val_loader))
sample_data = sample_data.to(device)

with torch.no_grad():
    latent_space = model.get_latent(sample_data)
    reconstructed_data = model(sample_data)

# On cpu
sample_data_np = sample_data.cpu().numpy()
latent_space_np = latent_space.cpu().numpy()
reconstructed_data_np = reconstructed_data.cpu().numpy()


# ==========================================
# PLOT 1: LATENT SPACE
# ==========================================
plt.figure(figsize=(12, 5))
plt.suptitle("Distribution of 8 variables of Latent Space for Background Validation", fontsize=16, fontweight='bold')

for i in range(lat_dim):
    plt.subplot(2, 4, i+1)
    plt.hist(latent_space_np[:, i], bins=10, color='teal', alpha=0.7, edgecolor='black')
    plt.title(f"Latent Dim: {i+1}")
    plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.subplots_adjust(top=0.9)
plt.show()

#@title Reconstruction of one event

# 1. Compatta i dati di tutti gli eventi in un unico DataFrame ordinato per pT
data = []
for ev_idx in range(len(sample_data_np)):
    o_s = sample_data_np[ev_idx][np.argsort(sample_data_np[ev_idx][:, 0])[::-1]]
    r_s = reconstructed_data_np[ev_idx][np.argsort(reconstructed_data_np[ev_idx][:, 0])[::-1]]
    for p_idx in range(len(o_s)):
        for i, lbl in enumerate(['pT', 'Eta', 'Phi']):
            data.append([ev_idx, p_idx, lbl, o_s[p_idx, i], 'Original'])
            data.append([ev_idx, p_idx, lbl, r_s[p_idx, i], 'Reconstructed'])

df = pd.DataFrame(data, columns=['Evento', 'Particle Index', 'Metric', 'Value', 'Type'])

# 2. Genera il plot con lo slider dell'evento integrato e i 3 subplot (pT, Eta, Phi)
fig = px.line(df, x='Particle Index', y='Value', color='Type', facet_col='Metric',
              animation_frame='Evento', markers=True, category_orders={'Metric': ['pT', 'Eta', 'Phi']})

# --- MODIFICHE PER LAYOUT ED ASSI DINAMICI ---

# 1. Applica in modo pulito l'indipendenza degli assi e mostra i tick su OGNI subplot
fig.update_yaxes(
    matches=None,
    showticklabels=True,
    autorange=True,
    title_text=""
)

# 2. Configura i margini globali (effetto tight_layout)
fig.update_layout(
    margin=dict(l=50, r=20, t=50, b=50), # Compatta gli spazi vuoti
    height=450
)

# 3. Forza Plotly a ricalcolare i limiti degli assi Y (autorange) ad ogni cambio frame
if fig.layout.updatemenus:
    for button in fig.layout.updatemenus[0].buttons:
        if "args" in button and len(button.args) > 1 and "frame" in button.args[1]:
            button.args[1]["frame"]["redraw"] = True

if fig.layout.sliders:
    for step in fig.layout.sliders[0].steps:
        if "args" in step and len(step.args) > 1 and "frame" in step.args[1]:
            step.args[1]["frame"]["redraw"] = True
print("CLiccare su autosclae in alto a dx del plot per riscalare gli assi")
fig.show()

"""# 2.1 Metodi di clusterizzazione classica"""

#@title Extraction of Latent Space
print("Starting Latent Space extraction (8D)...")

# Ensure the model is in evaluation mode
model.eval()

def extract_latent_space(dataloader):
    latent_vectors = []
    with torch.no_grad():
        for batch_x, _ in dataloader:
            batch_x = batch_x.to(device)
            # Use the encoder!
            latent = model.get_latent(batch_x)
            latent_vectors.append(latent.cpu().numpy())

    # Combine all batches into a single large numpy array
    return np.vstack(latent_vectors)

# For Anomaly Detection, we need the entire background (train + val)
# Create a single DataLoader without shuffle to extract everything in order
X_bg_full_tensor = torch.tensor(j1_background_scaled, dtype=torch.float32)
bg_full_loader = DataLoader(TensorDataset(X_bg_full_tensor, X_bg_full_tensor),
                            batch_size=batch_size,
                            shuffle=False)

# Extracting!
latent_bg = extract_latent_space(bg_full_loader)
latent_test = extract_latent_space(test_loader)

print(f"Dimensions Background Latent: {latent_bg.shape}")
print(f"Dimensions BlackBox Latent: {latent_test.shape}")

# # Save these new lightweight datasets, they will be the starting point for the Quantum Kernel!
save_dir = 'processed_data'
np.save(os.path.join(save_dir, 'latent_bg.npy'), latent_bg)
np.save(os.path.join(save_dir, 'latent_blackbox.npy'), latent_test)

print("Latent datasets successfully saved to Drive!")

"""## Reconstruction-loss anomaly detection"""

#@title Reconstruction loss
from sklearn.metrics import accuracy_score, roc_curve, auc
model.eval()
reconstruction_scores = []
with torch.no_grad():
    for batch_x, _ in test_loader:
        batch_x = batch_x.to(device)
        reconstructed = model(batch_x)

        loss_per_event = criterion(reconstructed, batch_x)
        # Save results correctly
        reconstruction_scores.append(loss_per_event.cpu().numpy())

reconstruction_scores = np.array(reconstruction_scores)


true_labels = true_labels_full[:len(reconstruction_scores)]

fpr, tpr, thresholds = roc_curve(true_labels, reconstruction_scores)
roc_auc = auc(fpr, tpr)
best_idx = np.argmax(tpr - fpr)
best_threshold = thresholds[best_idx]
predictions = (reconstruction_scores > best_threshold).astype(int)

acc = accuracy_score(true_labels, predictions)

print(f"Accuracy: {acc:.4f}, Auc: {roc_auc:.4f}")



# Create a single figure with 2 subplots side-by-side
fig, axes = plt.subplots(1, 2, figsize=(8, 4))

# Subplot 1: Histogram Visualization
axes[0].hist(reconstruction_scores[true_labels == 0], bins=100, color='royalblue', alpha=0.6, density=True, label='Background')
axes[0].hist(reconstruction_scores[true_labels == 1], bins=100, color='crimson', alpha=0.8, density=True, label='Anomalies')
axes[0].set_title(f"Reconstruction-Loss Anomaly Score", fontsize=12)
axes[0].set_xlabel("Loss", fontsize=11)
axes[0].set_ylabel("Density", fontsize=11)
axes[0].set_xscale('log')
axes[0].legend()
axes[0].grid(True, linestyle='--', alpha=0.4)

# Subplot 2: ROC Curve
axes[1].plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.3f})')
axes[1].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
axes[1].set_xlim([0.0, 1.0])
axes[1].set_ylim([0.0, 1.05])
axes[1].set_title(f"Receiver Operating Characteristic (ROC)", fontsize=12)
axes[1].set_xlabel('False Positive Rate', fontsize=11)
axes[1].set_ylabel('True Positive Rate', fontsize=11)
axes[1].legend(loc="lower right")
axes[1].grid(True, linestyle='--', alpha=0.4)

plt.tight_layout()
plt.show()

"""## K MEANS"""

#@title K-Means: ricerca migliore numero di cluster
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA


# ==========================================
# 1. CARICAMENTO DATI E LABEL (invariato)
# ==========================================
print("Caricamento dati latenti e label...")
save_dir = '/content/drive/MyDrive/set dati machine learning/processed_data'
latent_bg = np.load(os.path.join(save_dir, 'latent_bg.npy'))
latent_blackbox = np.load(os.path.join(save_dir, 'latent_blackbox.npy'))

true_labels = true_labels_full[:latent_blackbox.shape[0]]

# ==========================================
# 2. NORMALIZZAZIONE (invariata)
# ==========================================
scaler_l = StandardScaler()
latent_bg_norm = scaler_l.fit_transform(latent_bg)
latent_blackbox_norm = scaler_l.transform(latent_blackbox)

# ==========================================
# 3. CICLO SU K
# ==========================================
k_values = list(range(2, 21))  # prova k=2,3,...,20 — modifica a piacere

results = []  # lista di dict con tutti i risultati per ogni k

print(f"\nCiclo K-Means per k = {k_values[0]} ... {k_values[-1]}\n")

for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
    kmeans.fit(latent_bg_norm)

    distances = kmeans.transform(latent_blackbox_norm)
    scores = np.min(distances, axis=1)

    fpr, tpr, _ = roc_curve(true_labels, scores)
    roc_auc = auc(fpr, tpr)

    if roc_auc < 0.5:
        roc_auc = 1 - roc_auc
        scores = -scores
        fpr, tpr, _ = roc_curve(true_labels, scores)

    results.append({
        'k': k,
        'kmeans': kmeans,
        'scores': scores,
        'fpr': fpr,
        'tpr': tpr,
        'auc': roc_auc,
        'inertia': kmeans.inertia_
    })

    print(f"  k={k:2d} | AUC = {roc_auc:.4f} | Inertia = {kmeans.inertia_:.1f}")

# Miglior k per AUC
best = max(results, key=lambda x: x['auc'])
print(f"\n---> MIGLIOR K: {best['k']} con AUC = {best['auc']:.4f}")

# ==========================================
# 4. PLOT 1: AUC e Inertia al variare di k
# ==========================================
ks    = [r['k']       for r in results]
aucs  = [r['auc']     for r in results]
inertias = [r['inertia'] for r in results]

fig, (ax_auc, ax_in) = plt.subplots(1, 2, figsize=(10, 5))

ax_auc.plot(ks, aucs, marker='o', linewidth=2, color='royalblue')
ax_auc.axvline(best['k'], color='crimson', linestyle='--', label=f"Miglior k={best['k']} (AUC={best['auc']:.3f})")
ax_auc.set_xlabel("Numero di cluster k", fontsize=12)
ax_auc.set_ylabel("AUC", fontsize=12)
ax_auc.set_title("AUC vs numero di cluster", fontsize=14, fontweight='bold')
ax_auc.legend()
ax_auc.grid(True, linestyle='--', alpha=0.4)

# Elbow plot (inertia) — utile per capire quanti cluster sono "naturali"
ax_in.plot(ks, inertias, marker='o', linewidth=2, color='darkorange')
ax_in.axvline(best['k'], color='crimson', linestyle='--', label=f"Miglior k={best['k']}")
ax_in.set_xlabel("Numero di cluster k", fontsize=12)
ax_in.set_ylabel("Inertia (within-cluster SSE)", fontsize=12)
ax_in.set_title("Elbow Plot", fontsize=14, fontweight='bold')
ax_in.legend()
ax_in.grid(True, linestyle='--', alpha=0.4)

plt.tight_layout()
plt.show()

# ==========================================
# 5. PLOT 2: ROC curve di tutti i k sovrapposti
# ==========================================
plt.figure(figsize=(6, 4))
cmap = plt.cm.viridis(np.linspace(0, 1, len(results)))

for r, color in zip(results, cmap):
    lw = 3 if r['k'] == best['k'] else 1
    alpha = 1.0 if r['k'] == best['k'] else 0.4
    plt.plot(r['fpr'], r['tpr'], color=color, linewidth=lw, alpha=alpha,
             label=f"k={r['k']} (AUC={r['auc']:.3f})")

plt.plot([0, 1], [0, 1], 'k--', alpha=0.4)
plt.xlabel("False Positive Rate", fontsize=12)
plt.ylabel("True Positive Rate", fontsize=12)
plt.title("ROC Curve — tutti i k", fontsize=14, fontweight='bold')
plt.legend(fontsize=8, loc='lower right', ncol=2)
plt.grid(True, linestyle='--', alpha=0.4)
plt.show()

#@title PCA
# ==========================================
# 6. PLOT 3: dettaglio sul miglior k (i tuoi grafici originali)
# ==========================================
print(f"\nDettaglio per il miglior k={best['k']}...")

pca = PCA(n_components=3)
latent_3d = pca.fit_transform(latent_blackbox_norm)
cluster_centers_3d = pca.transform(best['kmeans'].cluster_centers_)

true_normal_3d   = latent_3d[true_labels == 0]
true_anomaly_3d  = latent_3d[true_labels == 1]
sample_size_norm = min(5000, len(true_normal_3d))

plt.figure(figsize=(5, 3))
plt.hist(best['scores'][true_labels == 0], bins=80, color='royalblue',
         alpha=0.6, density=True, label='Eventi Normali')
plt.hist(best['scores'][true_labels == 1], bins=80, color='crimson',
         alpha=0.8, density=True, label='Vere Anomalie')
plt.title(f"Anomaly Score K-Means k={best['k']} (AUC={best['auc']:.3f})", fontsize=12, fontweight='bold')
plt.xlabel("Distanza dal Cluster", fontsize=11)
plt.ylabel("Densità", fontsize=11)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()
import plotly.express as px

# Create the base traces using numpy arrays directly
fig_norm = px.scatter_3d(x=true_normal_3d[:sample_size_norm, 0], y=true_normal_3d[:sample_size_norm, 1], z=true_normal_3d[:sample_size_norm, 2])
fig_anom = px.scatter_3d(x=true_anomaly_3d[:, 0], y=true_anomaly_3d[:, 1], z=true_anomaly_3d[:, 2])
fig_cent = px.scatter_3d(x=cluster_centers_3d[:, 0], y=cluster_centers_3d[:, 1], z=cluster_centers_3d[:, 2])

# Combine traces into one figure and apply styles in a single step
fig_3d = fig_norm.add_traces(list(fig_anom.data) + list(fig_cent.data))
styles = [('Normali', 'royalblue', 'circle', 3, 0.1), ('Anomalie', 'crimson', 'circle', 6, 0.8), ('Centri Cluster', 'yellow', 'diamond', 12, 1.0)]

for trace, (name, color, symbol, size, opacity) in zip(fig_3d.data, styles):
    trace.update(name=name, showlegend=True, marker=dict(color=color, symbol=symbol, size=size, opacity=opacity))

fig_3d.update_layout(title=f"Spazio Latente K-Means k={best['k']} (PCA 3D)",width=500,   # Larghezza in pixel
                     height=400,
                     scene=dict(xaxis_title='PCA 1', yaxis_title='PCA 2', zaxis_title='PCA 3'), margin=dict(l=0, r=0, b=0, t=40))
fig_3d.show()

# Variabile kmeans aggiornata al miglior k (compatibile con il resto del notebook)
kmeans = best['kmeans']
anomaly_scores = best['scores']
k_clusters = best['k']
roc_auc = best['auc']

"""## T-SNE
Da decommentare maybe prima di consegnare
"""

#@title tsne
# from sklearn.manifold import TSNE


# # ==========================================
# # 5. GRAFICI CON t-SNE (2D)
# # ==========================================
# print("\nPreparazione dati per t-SNE...")

# # 1. Trovo gli indici di background (0) e anomalie (1)
# idx_normal = np.where(true_labels == 0)[0]
# idx_anomaly = np.where(true_labels == 1)[0]

# # 2. Sottocampiono i normali a 5000 per non far esplodere i tempi del t-SNE
# np.random.seed(42)
# sample_size = min(5000, len(idx_normal))
# idx_normal_sub = np.random.choice(idx_normal, sample_size, replace=False)

# # 3. Unisco gli indici delle anomalie con quelli del background sottocampionato
# idx_tsne = np.concatenate([idx_normal_sub, idx_anomaly])

# # 4. Estraggo i dati e le label corrispondenti
# latent_for_tsne = latent_blackbox_norm[idx_tsne]
# labels_for_tsne = true_labels[idx_tsne]

# print(f"Calcolo t-SNE su {len(latent_for_tsne)} eventi (potrebbe richiedere un paio di minuti)...")
# # Inizializzo e calcolo il t-SNE
# tsne = TSNE(n_components=2, random_state=42, perplexity=30, max_iter=1000)
# latent_2d_tsne = tsne.fit_transform(latent_for_tsne)

# # Separazione per il plot
# tsne_normali = latent_2d_tsne[labels_for_tsne == 0]
# tsne_anomalie = latent_2d_tsne[labels_for_tsne == 1]

# # Creazione del Plot
# fig = plt.figure(figsize=(10, 8))

# # Disegno prima i normali (in blu)
# plt.scatter(tsne_normali[:, 0], tsne_normali[:, 1],
#             c='royalblue', alpha=0.3, label='Normali', s=15)

# # Disegno sopra le anomalie (in rosso)
# plt.scatter(tsne_anomalie[:, 0], tsne_anomalie[:, 1],
#             c='crimson', alpha=0.9, label='Anomalie', s=35, edgecolors='black')

# plt.title("Visualizzazione dello Spazio Latente (t-SNE 2D)", fontsize=16, fontweight='bold')
# plt.xlabel("t-SNE Dimensione 1", fontsize=12)
# plt.ylabel("t-SNE Dimensione 2", fontsize=12)
# plt.legend(fontsize=12)
# plt.grid(True, linestyle='--', alpha=0.4)

# plt.tight_layout()
# plt.show()

"""## Gaussian Mixture Model"""

#@title GMM: ricerca migliore numero di componenti
from sklearn.mixture import GaussianMixture
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
import numpy as np

# ==========================================
# CICLO SUL NUMERO DI COMPONENTI
# ==========================================
n_values = list(range(2, 15))  # prova n=2,3,...,20 — modifica a piacere

results_gmm = []

print(f"Ciclo GMM per n_components = {n_values[0]} ... {n_values[-1]}\n")

for n in n_values:
    gmm = GaussianMixture(n_components=n, covariance_type='full', random_state=42)
    gmm.fit(latent_bg_norm)

    scores = -gmm.score_samples(latent_blackbox_norm)

    fpr, tpr, _ = roc_curve(true_labels, scores)
    roc_auc = auc(fpr, tpr)

    if roc_auc < 0.5:
        roc_auc = 1 - roc_auc
        scores = -scores
        fpr, tpr, _ = roc_curve(true_labels, scores)

    results_gmm.append({
        'n': n,
        'gmm': gmm,
        'scores': scores,
        'fpr': fpr,
        'tpr': tpr,
        'auc': roc_auc,
        'bic': gmm.bic(latent_bg_norm)   # BIC: misura qualità fit (più basso = meglio)
    })

    print(f"  n={n:2d} | AUC = {roc_auc:.4f} | BIC = {gmm.bic(latent_bg_norm):.1f}")

best_gmm = max(results_gmm, key=lambda x: x['auc'])
print(f"\n---> MIGLIOR N: {best_gmm['n']} con AUC = {best_gmm['auc']:.4f}")

# ==========================================
# PLOT 1: AUC e BIC al variare di n
# ==========================================
ns   = [r['n']   for r in results_gmm]
aucs = [r['auc'] for r in results_gmm]
bics = [r['bic'] for r in results_gmm]

fig, (ax_auc, ax_bic) = plt.subplots(1, 2, figsize=(14, 5))

ax_auc.plot(ns, aucs, marker='o', linewidth=2, color='royalblue')
ax_auc.axvline(best_gmm['n'], color='crimson', linestyle='--',
               label=f"Miglior n={best_gmm['n']} (AUC={best_gmm['auc']:.3f})")
ax_auc.set_xlabel("Numero di componenti", fontsize=12)
ax_auc.set_ylabel("AUC", fontsize=12)
ax_auc.set_title("AUC vs numero di componenti GMM", fontsize=14, fontweight='bold')
ax_auc.legend()
ax_auc.grid(True, linestyle='--', alpha=0.4)

# BIC: analogo dell'elbow plot per il GMM
ax_bic.plot(ns, bics, marker='o', linewidth=2, color='darkorange')
ax_bic.axvline(best_gmm['n'], color='crimson', linestyle='--',
               label=f"Miglior n={best_gmm['n']}")
ax_bic.set_xlabel("Numero di componenti", fontsize=12)
ax_bic.set_ylabel("BIC (più basso = fit migliore)", fontsize=12)
ax_bic.set_title("BIC Plot", fontsize=14, fontweight='bold')
ax_bic.legend()
ax_bic.grid(True, linestyle='--', alpha=0.4)

plt.tight_layout()
plt.show()

# ==========================================
# PLOT 2: ROC curve di tutti gli n sovrapposti
# ==========================================
plt.figure(figsize=(6, 4))
cmap = plt.cm.viridis(np.linspace(0, 1, len(results_gmm)))

for r, color in zip(results_gmm, cmap):
    lw    = 3   if r['n'] == best_gmm['n'] else 1
    alpha = 1.0 if r['n'] == best_gmm['n'] else 0.4
    plt.plot(r['fpr'], r['tpr'], color=color, linewidth=lw, alpha=alpha,
             label=f"n={r['n']} (AUC={r['auc']:.3f})")

plt.plot([0, 1], [0, 1], 'k--', alpha=0.4)
plt.xlabel("False Positive Rate", fontsize=12)
plt.ylabel("True Positive Rate", fontsize=12)
plt.title("ROC Curve — tutti gli n GMM", fontsize=14, fontweight='bold')
plt.legend(fontsize=8, loc='lower right', ncol=2)
plt.grid(True, linestyle='--', alpha=0.4)
plt.show()

# ==========================================
# PLOT 3: distribuzione score del miglior n (identico all'originale)
# ==========================================
plt.figure(figsize=(6, 4))
plt.hist(best_gmm['scores'][true_labels == 0], bins=80, color='royalblue',
         alpha=0.6, density=True, label='Eventi Normali (Background)')
plt.hist(best_gmm['scores'][true_labels == 1], bins=80, color='crimson',
         alpha=0.8, density=True, label='Vere Anomalie (Segnale)')
plt.title(f"Distribuzione Anomaly Score GMM  n={best_gmm['n']}  (AUC = {best_gmm['auc']:.3f})",
          fontsize=14, fontweight='bold')
plt.xlabel("Anomaly Score (-Log Probabilità)", fontsize=12)
plt.ylabel("Densità", fontsize=12)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.4)
plt.show()

# Variabili aggiornate al miglior n (compatibili col resto del notebook)
gmm              = best_gmm['gmm']
anomaly_scores_gmm = best_gmm['scores']
n_components     = best_gmm['n']
roc_auc_gmm      = best_gmm['auc']

"""##  Score ibrido"""

#@title Calcolo latenti + reconstruction score (base per anomaly detection)
import numpy as np

model.eval()

def get_latents_and_recon_scores(loader, model, device):
    all_latents = []
    all_recon_scores = []

    with torch.no_grad():
        for batch_x, _ in loader:
            batch_x = batch_x.to(device)
            recon = model(batch_x)
            latent = model.get_latent(batch_x)

            # Maschera particelle reali
            mask = (batch_x.abs().sum(dim=-1) > 0).float()  # (B, 50)

            # MODIFICA 4: score pesato per pT
            # le particelle più energetiche contribuiscono di più allo score
            pt = batch_x[:, :, 0].clamp(min=0)
            pt_weight = pt / (pt.sum(dim=-1, keepdim=True) + 1e-8)

            err = ((recon - batch_x) ** 2).sum(dim=-1)  # (B, 50)
            recon_score = (err * pt_weight * mask).sum(dim=-1)  # (B,)

            all_latents.append(latent.cpu().numpy())
            all_recon_scores.append(recon_score.cpu().numpy())

    return np.concatenate(all_latents), np.concatenate(all_recon_scores)

print("Calcolo latenti e score background...")
latent_bg_norm, recon_scores_bg = get_latents_and_recon_scores(train_loader, model, device)

print("Calcolo latenti e score BlackBox...")
latent_blackbox_norm, recon_scores_blackbox = get_latents_and_recon_scores(test_loader, model, device)

print(f"latent_bg_norm shape:       {latent_bg_norm.shape}")
print(f"latent_blackbox_norm shape: {latent_blackbox_norm.shape}")
print(f"recon_scores_bg shape:      {recon_scores_bg.shape}")
print(f"recon_scores_blackbox shape:{recon_scores_blackbox.shape}")

#@title  (ricostruzione pT-pesata + GMM) — NUOVA CELLA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_curve, auc
import numpy as np

# Normalizzazione separata dei due score (fondamentale prima di combinarli)
scaler_recon = StandardScaler()
scaler_gmm   = StandardScaler()

recon_bg_scaled       = scaler_recon.fit_transform(recon_scores_bg.reshape(-1, 1)).ravel()
recon_blackbox_scaled = scaler_recon.transform(recon_scores_blackbox.reshape(-1, 1)).ravel()

gmm_bg_scaled       = scaler_gmm.fit_transform((-gmm.score_samples(latent_bg_norm)).reshape(-1, 1)).ravel()
gmm_blackbox_scaled = scaler_gmm.transform((-gmm.score_samples(latent_blackbox_norm)).reshape(-1, 1)).ravel()

# Grid search su alpha per trovare la combinazione migliore
print("Grid search su alpha (ricostruzione vs GMM)...\n")
best_auc_hybrid = 0
best_alpha = 0

for alpha in np.arange(0.0, 1.05, 0.1):
    score = alpha * recon_blackbox_scaled + (1 - alpha) * gmm_blackbox_scaled
    fpr, tpr, _ = roc_curve(true_labels, score)
    roc_auc = auc(fpr, tpr)
    if roc_auc < 0.5:
        roc_auc = 1 - roc_auc
    print(f"  alpha={alpha:.1f} (recon) | AUC = {roc_auc:.4f}")
    if roc_auc > best_auc_hybrid:
        best_auc_hybrid = roc_auc
        best_alpha = alpha

print(f"\n---> MIGLIOR AUC IBRIDO: {best_auc_hybrid:.4f} con alpha={best_alpha:.1f}")

# Plot con il best alpha
best_score = best_alpha * recon_blackbox_scaled + (1 - best_alpha) * gmm_blackbox_scaled
fpr_h, tpr_h, _ = roc_curve(true_labels, best_score)
if auc(fpr_h, tpr_h) < 0.5:
    best_score = -best_score
    fpr_h, tpr_h, _ = roc_curve(true_labels, best_score)

plt.figure(figsize=(8, 5))
plt.hist(best_score[true_labels == 0], bins=80, color='royalblue', alpha=0.6,
         density=True, label='Background')
plt.hist(best_score[true_labels == 1], bins=80, color='crimson', alpha=0.8,
         density=True, label='Segnale')
plt.title(f"Score Ibrido (alpha={best_alpha:.1f}) — AUC = {best_auc_hybrid:.3f}", fontsize=14)
plt.xlabel("Anomaly Score", fontsize=12)
plt.ylabel("Densità", fontsize=12)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.4)
plt.show()

#@title Isolation Forest: ricerca migliore numero di estimators e contaminazione
from sklearn.ensemble import IsolationForest
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
import numpy as np

# ==========================================
# CICLO SU N_ESTIMATORS E CONTAMINAZIONE
# ==========================================
n_estimators_values = [50, 100, 200, 300, 500]
contamination_values = [0.01, 0.05, 0.1, 0.2, 'auto']

results_iso = []

print(f"Ciclo Isolation Forest...\n")

for n_est in n_estimators_values:
    for cont in contamination_values:

        iso = IsolationForest(n_estimators=n_est, contamination=cont, random_state=42, n_jobs=-1)
        iso.fit(latent_bg_norm)

        scores = -iso.score_samples(latent_blackbox_norm)

        fpr, tpr, _ = roc_curve(true_labels, scores)
        roc_auc = auc(fpr, tpr)

        if roc_auc < 0.5:
            roc_auc = 1 - roc_auc
            scores = -scores
            fpr, tpr, _ = roc_curve(true_labels, scores)

        results_iso.append({
            'n_estimators': n_est,
            'contamination': cont,
            'iso': iso,
            'scores': scores,
            'fpr': fpr,
            'tpr': tpr,
            'auc': roc_auc,
        })

        print(f"  n_est={n_est:3d} | cont={str(cont):5s} | AUC = {roc_auc:.4f}")

best_iso = max(results_iso, key=lambda x: x['auc'])
print(f"\n---> MIGLIOR COMBINAZIONE: n_estimators={best_iso['n_estimators']}, "
      f"contamination={best_iso['contamination']} con AUC = {best_iso['auc']:.4f}")

# ==========================================
# PLOT 1: AUC heatmap (n_estimators x contamination)
# ==========================================
import numpy as np

cont_labels = [str(c) for c in contamination_values]
auc_matrix = np.zeros((len(n_estimators_values), len(contamination_values)))

for r in results_iso:
    i = n_estimators_values.index(r['n_estimators'])
    j = contamination_values.index(r['contamination'])
    auc_matrix[i, j] = r['auc']

fig, ax = plt.subplots(figsize=(8, 4))
im = ax.imshow(auc_matrix, cmap='viridis', aspect='auto',
               vmin=auc_matrix.min(), vmax=auc_matrix.max())
plt.colorbar(im, ax=ax, label='AUC')

ax.set_xticks(range(len(contamination_values)))
ax.set_xticklabels(cont_labels, fontsize=11)
ax.set_yticks(range(len(n_estimators_values)))
ax.set_yticklabels(n_estimators_values, fontsize=11)
ax.set_xlabel("Contamination", fontsize=12)
ax.set_ylabel("N Estimators", fontsize=12)
ax.set_title("AUC Isolation Forest (n_estimators × contamination)", fontsize=14, fontweight='bold')

# Scrivi il valore AUC in ogni cella
for i in range(len(n_estimators_values)):
    for j in range(len(contamination_values)):
        ax.text(j, i, f"{auc_matrix[i, j]:.3f}", ha='center', va='center',
                color='white' if auc_matrix[i, j] < auc_matrix.mean() else 'black', fontsize=9)

# Evidenzia la cella migliore
best_i = n_estimators_values.index(best_iso['n_estimators'])
best_j = contamination_values.index(best_iso['contamination'])
ax.add_patch(plt.Rectangle((best_j - 0.5, best_i - 0.5), 1, 1,
                             fill=False, edgecolor='crimson', linewidth=3))

plt.tight_layout()
plt.show()

# Creiamo un'unica figura con 1 riga e 3 colonne di subplot
fig, axs = plt.subplots(1, 3, figsize=(15, 4))

# ==========================================
# SUBPLOT 1: AUC vs n_estimators per ogni contamination
# ==========================================
ax = axs[0]
for j, cont in enumerate(contamination_values):
    aucs_line = [auc_matrix[i, j] for i in range(len(n_estimators_values))]
    ax.plot(n_estimators_values, aucs_line, marker='o', linewidth=2, label=f"cont={cont}")

ax.axvline(best_iso['n_estimators'], color='crimson', linestyle='--',
           label=f"Miglior n_est={best_iso['n_estimators']}")
ax.set_xlabel("N Estimators", fontsize=11)
ax.set_ylabel("AUC", fontsize=11)
ax.set_title("AUC vs N Estimators per Contamination", fontsize=12, fontweight='bold')
ax.legend(fontsize=9, loc='lower right')
ax.grid(True, linestyle='--', alpha=0.4)

# ==========================================
# SUBPLOT 2: ROC curve di tutte le combinazioni
# ==========================================
ax = axs[1]
cmap = plt.cm.viridis(np.linspace(0, 1, len(results_iso)))

for r, color in zip(results_iso, cmap):
    is_best = (r['n_estimators'] == best_iso['n_estimators'] and
               r['contamination'] == best_iso['contamination'])
    lw    = 3   if is_best else 0.8
    alpha = 1.0 if is_best else 0.3
    ax.plot(r['fpr'], r['tpr'], color=color, linewidth=lw, alpha=alpha,
             label=f"n={r['n_estimators']},c={r['contamination']} ({r['auc']:.3f})" if is_best else None)

ax.plot([0, 1], [0, 1], 'k--', alpha=0.4)
ax.set_xlabel("False Positive Rate", fontsize=11)
ax.set_ylabel("True Positive Rate", fontsize=11)
ax.set_title("ROC Curve — miglior Isolation Forest", fontsize=12, fontweight='bold')
ax.legend(fontsize=9, loc='lower right')
ax.grid(True, linestyle='--', alpha=0.4)

# ==========================================
# SUBPLOT 3: distribuzione score del miglior modello
# ==========================================
ax = axs[2]
ax.hist(best_iso['scores'][true_labels == 0], bins=80, color='royalblue',
         alpha=0.6, density=True, label='Eventi Normali (Background)')
ax.hist(best_iso['scores'][true_labels == 1], bins=80, color='crimson',
         alpha=0.8, density=True, label='Vere Anomalie (Segnale)')
ax.set_title(f"Anomaly Score (AUC={best_iso['auc']:.3f})\n"
             f"n={best_iso['n_estimators']}, cont={best_iso['contamination']}",
             fontsize=12, fontweight='bold')
ax.set_xlabel("Anomaly Score", fontsize=11)
ax.set_ylabel("Densità", fontsize=11)
ax.legend(fontsize=9)
ax.grid(True, linestyle='--', alpha=0.4)

# --- EFFETTO TIGHT LAYOUT ---
# Ottimizza gli spazi tra i subplot per evitare che scritte e assi si sovrappongano
plt.tight_layout()
plt.show()
# Variabili aggiornate al miglior modello (compatibili col resto del notebook)
iso              = best_iso['iso']
scores_iso       = best_iso['scores']
roc_auc_iso      = best_iso['auc']

"""# 3) Unsupervised Quantum Kernel Method"""

pip install --upgrade qiskit qiskit-machine-learning qiskit-algorithms

import numpy as np
from sklearn.svm import OneClassSVM
from qiskit.circuit.library import ZZFeatureMap
from qiskit_machine_learning.kernels import FidelityQuantumKernel

"""## Quantum Feature Map"""

import numpy as np
import matplotlib.pyplot as plt
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector

# 1. Definizione dei parametri principali
dim_latent = 8          # Dimensione del tuo latent_background
n_q = dim_latent // 2     # Numero di qubit (8 / 2 = 4)

# Fissa qui il numero L di volte in cui vuoi ripetere la Feature Map
L = 3

# 2. Creazione del vettore di parametri simbolici (x0, x1, ..., x7)
x = ParameterVector('x', dim_latent)

# 3. Costruzione della Feature Map
feature_map = QuantumCircuit(n_q)

# Ripetiamo l'intera mappa L volte a cascata
for layer in range(L):

    # --- STRATO 1: Prime porte G ---
    # Per ogni qubit i, i parametri sono x[2*i] e x[2*i+1]
    # Matrice G(pi/2, x_2i, x_2i+1)
    for i in range(n_q):
        feature_map.u(np.pi / 2, x[2 * i], x[2 * i + 1], i)

    # Inseriamo una barriera visiva opzionale per separare i blocchi nel disegno
    feature_map.barrier()

    # --- STRATO 2: Entanglement (La scatola grigia centrale con CNOT a scala) ---
    # Connette il qubit i con il qubit i+1
    for i in range(n_q - 1):
        feature_map.cx(i, i + 1)

    feature_map.barrier()

    # --- STRATO 3: Seconde porte G ---
    # Matrice G(x_2i, x_2i+1, 0)
    for i in range(n_q):
        feature_map.u(x[2 * i], x[2 * i + 1], 0, i)

    # Inseriamo una barriera alla fine del layer per distinguerlo dal successivo (se L > 1)
    if layer < L - 1:
        feature_map.barrier()

# 4. Stampa e Visualizzazione della Feature Map
print(f"--- FEATURE MAP GENERATA (Ripetuta L = {L} volte) ---")

# Opzione A: Stampa testuale direttamente sulla console/terminale
print(feature_map.draw(output='text'))

# Opzione B: Generazione della figura grafica (Matplotlib)
# Se sei all'interno di un Jupyter Notebook, basta eseguire la riga sotto:
# feature_map.draw(output='mpl')

# Opzione C: Generazione del codice o figura in formato LaTeX
# feature_map.draw(output='latex')

import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector
# Nota: a seconda della versione di qiskit-machine-learning, l'import potrebbe variare
# da qiskit_machine_learning.kernels import TrainableFidelityQuantumKernel
from qiskit_machine_learning.kernels import FidelityQuantumKernel


# 2. DEFINIZIONE DELLA STRUTTURA DELLA FEATURE MAP (Simbolica)
dim_latent = len(latent_bg[1])
n_q = dim_latent // 2
L = 3  # Numero di ripetizioni della mappa

x = ParameterVector('x', dim_latent)
feature_map = QuantumCircuit(n_q)

for layer in range(L):
    # Strato 1: G(pi/2, x_2i, x_2i+1)
    for i in range(n_q):
        feature_map.u(np.pi / 2, x[2 * i], x[2 * i + 1], i)
    feature_map.barrier()

    # Strato 2: Entanglement lineare
    for i in range(n_q - 1):
        feature_map.cx(i, i + 1)
    feature_map.barrier()

    # Strato 3: G(x_2i, x_2i+1, 0)
    for i in range(n_q):
        feature_map.u(x[2 * i], x[2 * i + 1], 0, i)
    if layer < L - 1:
        feature_map.barrier()


# 3. CREAZIONE DEL KERNEL QUANTISTICO
# Lasciamo che Qiskit gestisca la fedeltà e le primitive in background
fidelity_kernel = FidelityQuantumKernel(feature_map=feature_map)

"""## Training"""

#DIVIDO I DATI IN TRAIN E TEST
from sklearn.model_selection import train_test_split

# 1. CARICAMENTO DATI REALI
# (Ipotizzo che tu abbia già caricato/generato il tuo array 'latent_bg' reale prima di questo punto)

# Dividiamo il dataset: ad esempio, l'80% per il training e il 20% per il test
latent_train, latent_test = train_test_split(
    latent_bg,
    test_size=0.20,      # Specifica che il 20% dei dati va nel test set
    random_state=42      # (Opzionale) Fissa il seed per avere sempre la stessa divisione se riavvii il codice
)

print(f"Dimensione totale originale: {latent_bg.shape}")
print(f"Dati assegnati al Training: {latent_train.shape}")
print(f"Dati assegnati al Test: {latent_test.shape}")

#RIDUCO LE DIMENSIONI DI latent_test e latent_train
# Estrae i primi 100 eventi (dalla riga 0 alla riga 99)
latent_train_100 = latent_train[:100]

# Fa la stessa cosa per il dataset di test
latent_test_100 = latent_test[:100]

# Stampa di controllo per verificare le nuove dimensioni
print(f"Nuova dimensione training set: {latent_train_100.shape}")
print(f"Nuova dimensione test set: {latent_test_100.shape}")

# CALCOLO DELLA MATRICE KERNEL DI ADDESTRAMENTO
# Questo comando prende la feature map, sostituisce i parametri 'x' con i numeri di latent_bg
# ed esegue i circuiti per darti la matrice finale.
print("Calcolo della matrice di Kernel per il training...")
kernel_matrix_train = fidelity_kernel.evaluate(x_vec=latent_train_100)

print("\n--- MATRICE KERNEL DI ADDESTRAMENTO GENERATA ---")
print(f"Dimensione della matrice: {kernel_matrix_train.shape}") # Sarà una matrice N_train x N_train con elementi diagonali 1.0
print(kernel_matrix_train)

"""# COMMENTO UN CODICE DELLA FEATURE MAP CHE NON UTILIZZA QISKIT

"""

#NOTA: questo codice usa le dimensioni n_q sbagliate e assegna alla matrice G i parametri sbagliati!!!
# (però fa capire cosa succede in qiskit)
'''#import numpy as np
#from qiskit import QuantumCircuit
#from qiskit.circuit import ParameterVector
#import matplotlib.pyplot as plt

# ──────────────────────────────────────────────────────────────────
#  PARAMETRI — modifica qui
# ──────────────────────────────────────────────────────────────────
#L   = 2    # numero di ripetizioni della feature map
#n_q = 4    # numero di qubit  (= len(x) / 2 = 8 / 2)
#            x ha dimensione 2 * n_q = 8
# ──────────────────────────────────────────────────────────────────


#def build_feature_map(L: int, n_q: int) -> QuantumCircuit:
    """
    Costruisce il circuito U(x) come QuantumCircuit Qiskit con
    ParameterVector (così può essere bindato a dati reali).

    Struttura di ogni layer:
      Strato A : U(π/2, x_{2i}, x_{2i+1})  su qubit i   [gate SU(2)]
      Strato B : CNOT tra qubit adiacenti   (entanglement)
      Strato C : U(x_{2i}, x_{2i+1}, 0)    su qubit i   [gate SU(2)]

    Le feature x_{2i} e x_{2i+1} sono condivise tra tutti i layer
    (stesso ParameterVector x, stessi simboli — il binding avviene
    una volta sola quando si passa il dato reale).

    Parametri
    ---------
    L   : int  — numero di ripetizioni
    n_q : int  — numero di qubit (= len(x_data) // 2)

    Ritorna
    -------
    qc : QuantumCircuit  con 2*n_q parametri simbolici (x[0]…x[2n_q-1])
    """
    # ParameterVector x di dimensione 2*n_q (una volta sola,
    # condiviso tra tutti i layer)
 #   x = ParameterVector('x', 2 * n_q)

  #  qc = QuantumCircuit(n_q, name=f'U(x) L={L}')

   # for _ in range(L):

        # ── Strato A : U(π/2, x_{2i}, x_{2i+1}) su ogni qubit ──
    #    for i in range(n_q):
     #       qc.u(np.pi / 2, x[2 * i], x[2 * i + 1], i)

      #  qc.barrier()

        # ── Strato B : CNOT adiacenti (entanglement) ─────────────
       # for i in range(n_q - 1):
        #    qc.cx(i, i + 1)

        #qc.barrier()

        # ── Strato C : U(x_{2i}, x_{2i+1}, 0) su ogni qubit ─────
        #for i in range(n_q):
         #   qc.u(x[2 * i], x[2 * i + 1], 0, i)

        qc.barrier()

    return qc


# ══════════════════════════════════════════════════════════════════
#  Costruzione e stampa del circuito
# ══════════════════════════════════════════════════════════════════
qc = build_feature_map(L=L, n_q=n_q)

print(qc)
print(f"\nParametri simbolici : {list(qc.parameters)}")
print(f"Numero di gate      : {qc.size()}")
print(f"Profondità          : {qc.depth()}")

# ── Figura del circuito ──────────────────────────────────────────
fig = qc.draw(
    output='mpl',
    style='bw',
    fold=-1,                  # non va a capo
    plot_barriers=True,
    initial_state=True,       # mostra |0⟩ su ogni qubit
)

fig.suptitle(
    rf'Data Encoding Circuit $U(x)$ — $n_q={n_q}$ qubit, $L={L}$ layer'
    '\n'
    r'Strato A: $U(\pi/2,\,x_{2i},\,x_{2i+1})$   '
    r'Strato B: CNOT   '
    r'Strato C: $U(x_{2i},\,x_{2i+1},\,0)$   '
    r'$U(\theta,\phi,\lambda)\in SU(2)$',
    fontsize=11, fontweight='bold', y=1.02
)

plt.tight_layout()
plt.savefig('/mnt/user-data/outputs/quantum_feature_map_circuit.png',
            dpi=180, bbox_inches='tight')
plt.show()
print("\n[✓] Figura salvata in: quantum_feature_map_circuit.png")'''

"""## Inference"""

print("Avvio del calcolo della matrice Kernel di Test...")
print("Questa operazione potrebbe richiedere qualche minuto a seconda dell'hardware...\n")

# CALCOLO DELLA MATRICE DI TEST
# Attenzione ai parametri:
# x_vec = i dati nuovi che vogliamo classificare (Test)
# y_vec = i dati storici che il modello ha studiato (Train)
kernel_matrix_test = fidelity_kernel.evaluate(x_vec=latent_test_100, y_vec=latent_train_100)

print("--- MATRICE KERNEL DI TEST GENERATA CON SUCCESSO! ---")

# Stampiamo le dimensioni per sicurezza
print(f"Dimensioni della matrice: {kernel_matrix_test.shape}")
# Il risultato atteso qui è (100, 100) visto che abbiamo usato 100 eventi di test e 100 di train.

# Stampiamo un piccolo pezzo della matrice (le prime 3 righe e 3 colonne)
# per vedere che aspetto hanno le distanze quantistiche calcolate
print("\nAnteprima delle prime 3x3 celle della matrice:")
print(kernel_matrix_test[:3, :3])

"""## Plot della KPCA"""

from sklearn.decomposition import KernelPCA

# 1. RIDUZIONE DIMENSIONALE CON KERNEL PCA
print("Proiezione dello spazio quantistico in 3D tramite Kernel PCA...")

# Inizializziamo la Kernel PCA dicendole che abbiamo già calcolato noi il Kernel
kpca = KernelPCA(n_components=3, kernel='precomputed')

# FASE A: Costruiamo lo spazio 3D basandoci sull'addestramento
kpca.fit(kernel_matrix_train)

# FASE B: Proiettiamo i nostri dati di Test (che la SVM ha appena classificato) in questo spazio
dati_3d = kpca.transform(kernel_matrix_test)

# Estraiamo le coordinate X, Y, Z per il plot
x_coords = dati_3d[:, 0]
y_coords = dati_3d[:, 1]
z_coords = dati_3d[:, 2]

# 2. CREAZIONE DELLA FIGURA 3D
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# 3. DIVISIONE TRA NORMALI E ANOMALIE
# Usiamo le previsioni che sono uscite dal comando: previsioni = modello_quantistico.predict(kernel_matrix_test)
maschera_normali = (previsioni == 1)
maschera_anomalie = (previsioni == -1)

# Plottiamo i dati NORMALI (Palline blu)
ax.scatter(x_coords[maschera_normali],
           y_coords[maschera_normali],
           z_coords[maschera_normali],
           c='blue', marker='o', alpha=0.5, label='Background (Test)')

# Plottiamo le ANOMALIE (Croci rosse)
ax.scatter(x_coords[maschera_anomalie],
           y_coords[maschera_anomalie],
           z_coords[maschera_anomalie],
           c='red', marker='X', s=100, label='Anomalie Rilevate')

# 4. ESTETICA
ax.set_title("La Visione Quantistica della SVM\n(Kernel PCA dello Spazio di Hilbert)")
ax.set_xlabel("Componente Quantistica 1")
ax.set_ylabel("Componente Quantistica 2")
ax.set_zlabel("Componente Quantistica 3")
ax.legend()

plt.show()